export enum FEED_SEARCH_TYPE {
  POPULAR = 'POPULAR',
  USER_NICK_NAME = 'USER_NICK_NAME',
  CHALLENGE_TAG = 'CHALLENGE_TAG',
}

export enum SOCIAL_TYPE {
  KAKAO = 'KAKAO',
  APPLE = 'APPLE',
  NONE = 'NONE',
}

export enum ERRPR_CODE {
  DEFAULT = 'DEFAULT',
  VALIDATION_ERROR = 'VALIDATION_ERROR', // 예외처리 에러
  UNAUTHENTICATED = 'UNAUTHENTICATED', // 토큰 만료
  UNAUTHORIZED = 'UNAUTHORIZED', // 권한 없음
}

export enum CHALLENGES_SORT {
  BRAND_NEW = 'BRAND_NEW',
  POPLUAR = 'POPLUAR ',
}
